rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::GM6020Test -> gm6020_hardware
      - rmcs_core::controller::GM6020TestController -> gm6020_joystick
      - rmcs_core::controller::pid::PidController -> gm6020_velocity_pid

gm6020_hardware:
  ros__parameters:
    board_serial: ""
    motor_id: 1

gm6020_joystick:
  ros__parameters:
    mode: velocity
    max_velocity: 5.0
    max_angular_velocity: 3.0

gm6020_velocity_pid:
  ros__parameters:
    measurement: /motor/velocity_filtered
    setpoint: /motor/control_target
    control: /motor/control_torque
    kp: 0.14
    ki: 0.0003
    kd: 0.0
    output_max: 1.5
    output_min: -1.5
